routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resources([
    'post' => 'PostController'
]);

Route::post('/comment/{post_id}', 'CommentController@store');
//Route::get('/{user_id}', 'ProfileController@profile');

resources/views/layouts/partials/left_sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4" style="background: #e8519e; background: -webkit-linear-gradient(bottom, #e8519e, #c77ff2); background: -o-linear-gradient(bottom, #e8519e, #c77ff2); background: -moz-linear-gradient(bottom, #e8519e, #c77ff2); background: linear-gradient(bottom, #e8519e, #c77ff2);">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
      <img src="{{ asset('images/twitter-icon.svg') }}"
           class="brand-image mt-1 ml-4 mr-3"
           style="opacity: .8">
      <span class="brand-text font-weight-bold text-dark">Twitter</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user (optional) -->
      <div class="user-panel mt-1 pb-1 mb-1 d-flex">
        
        <div class="info nav nav-pills nav-sidebar flex-column"  data-widget="treeview" role="menu" data-accordion="false">
            <li class="nav-item has-treeview">
            <a href="#" class="nav-link media pl-1">
                <div>
                    <img src="{{ asset('images/profile-image.jpg') }}" class="img-size-50 mr-1 img-circle elevation-2" alt="User Image">
                </div>
                <div class="media-body pl-1">
                    <h3 class="dropdown-item-title font-weight-bold text-dark">
                        {{ Auth::user()->name }}
                    </h3>
                    <p class="text-sm font-weight-bold text-dark">@ {{ Auth::user()->username }}</p>
                </div>
                <span class="ml-2 font-weight-bold text-dark"><i class="fas fa-angle-down"></i></span>
            </a>
            <ul class="nav nav-treeview">
                <li class="nav-item">
                    <a href="#" class="nav-link font-weight-bold text-dark">
                        <i class="far fa-circle nav-icon"></i>
                        Your profile
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('logout') }}" class="nav-link font-weight-bold text-dark" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                        <i class="far fa-circle nav-icon"></i>
                        Log out       
                    </a>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </li>
            </ul>
            </li> 
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item menu-open">
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="#" class="nav-link font-weight-bold text-dark">
                  <i class="fas fa-home nav-icon"></i>
                  Home
                </a>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link font-weight-bold text-dark">
                  <i class="fas fa-hashtag nav-icon"></i>
                  Explore
                </a>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link font-weight-bold text-dark">
                  <i class="fas fa-bell nav-icon"></i>
                  Notifications
                </a>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link font-weight-bold text-dark">
                  <i class="fas fa-envelope nav-icon"></i>
                  Messages
                </a>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link font-weight-bold text-dark">
                  <i class="fas fa-bookmark nav-icon"></i>
                  Bookmarks
                </a>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link font-weight-bold text-dark">
                  <i class="fas fa-list-alt nav-icon"></i>
                  Lists
                </a>
              </li>
            </ul>
          </li><!-- 
          <a href="{{ route('post.create') }}" class="btn btn-light btn-block btn-lg text-dark mt-4" style="border-radius:50px">
            Tweet
          </a> -->
          <button type="button" class="btn btn-light btn-block btn-lg text-dark mt-4" style="border-radius:50px" data-toggle="modal" data-target="#exampleModalCenter">Tweet</button>
        </div>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

resources/views/layouts/partials/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light fixed-top" style="background: #c77ff2;">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item d-none d-sm-inline-block">
        <a href="/post" class="nav-link font-weight-bold text-dark">Home</a>
      </li>
    </ul>
    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <form class="form-inline ml-3">
            <div class="input-group input-group-sm">
                <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                    <button class="btn btn-navbar" type="submit">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>
        </form>
    </ul>
  </nav>

resources/views/layouts/partials/right_sidebar.blade.php
<div class="col-md-4  mt-5 pt-4 pr-0">

  <div class="card rounded" style="background: #c77ff2;  position: -webkit-sticky; position: sticky; top: 60px;">
    <div class="card-header">
      <h3 class="card-title">Trends for you</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body p-0">
      <ul class="products-list product-list-in-card pr-2">

        <li class="item pl-4 py-1" style="background: #c77ff2;">
          <a href="#" class="product-title text-dark"># Hashtag</a>
          <p>45k Tweets</p>
        </li>
        <li class="item pl-4 py-1" style="background: #c77ff2;">
          <a href="#" class="product-title text-dark"># Hashtag</a>
          <p>45k Tweets</p>
        </li>
        <li class="item pl-4 py-1" style="background: #c77ff2;">
          <a href="#" class="product-title text-dark"># Hashtag</a>
          <p>45k Tweets</p>
        </li>

      </ul>
    </div>
    <!-- /.card-body -->
  </div>

  <div class="card" style="background: #c77ff2;  position: -webkit-sticky; position: sticky; top: 290px;">
    <div class="card-header">
      <h3 class="card-title">Who to follow</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body p-0">
      <ul class="products-list product-list-in-card pl-3 pr-2">

        <li class="item" style="background: #c77ff2;">
          <div class="product-img">
            <img class="img-circle img-size-50" src="{{ asset('images/profile-image.jpg') }}" alt="User Image">  
          </div>
          <div class="product-info">
            <a href="#" class="product-title text-dark">name</a>
            <span><a class="btn btn-light btn-sm float-right mt-2 mr-3 py-2" href="#" style="border-radius:50px">Follow</a></span>
            <p>@username</p>     
          </div>
        </li>
        <li class="item" style="background: #c77ff2;">
          <div class="product-img">
            <img class="img-circle img-size-50" src="{{ asset('images/profile-image.jpg') }}" alt="User Image">  
          </div>
          <div class="product-info">
            <a href="#" class="product-title text-dark">name</a>
            <span><a class="btn btn-light btn-sm float-right mt-2 mr-3 py-2" href="#" style="border-radius:50px">Follow</a></span>
            <p>@username</p>     
          </div>
        </li>
        <li class="item" style="background: #c77ff2;">
          <div class="product-img">
            <img class="img-circle img-size-50" src="{{ asset('images/profile-image.jpg') }}" alt="User Image">  
          </div>
          <div class="product-info">
            <a href="#" class="product-title text-dark">name</a>
            <span><a class="btn btn-light btn-sm float-right mt-2 mr-3 py-2" href="#" style="border-radius:50px">Follow</a></span>
            <p>@username</p>     
          </div>
        </li>

      </ul>         
    </div>
  </div>

  <div class="description mb-3" style="position: -webkit-sticky; position: sticky; top: 565px;">
    <p class="text-dark">Copyright &copy; 2020 Twitter All rights reserved.</p>
  </div>
</div>

resources/views/layouts/partials/tweet_modal.blade.php
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content" style="background: #e8519e;">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Tweet</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <form action="/post" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="modal-body">
              <div class="form-group">
                <textarea rows = "7" class="form-control" id="content" name="content" placeholder="What's happening?"></textarea>
              </div>
              <div class="form-group">
                <label for="tags">Hashtag</label>
                <input type="text" class="form-control" id="tags" name="tags" placeholder="Use comma to seperate each word">
              </div>
            </div>
            <div class="modal-footer">
              <span>Add image to your post
                <input type="file" class="btn btn-light" name="image"></input>
                <button type="submit" class="btn btn-light float-right">Tweet</button>
              </span>
            </div>
          </form>
        </div>
      </div>
    </div>